DROP TABLE IF EXISTS public.users;

CREATE TABLE public.USERS(
   USER_ID SERIAL PRIMARY KEY,
   USERNAME VARCHAR  NOT NULL UNIQUE,
   PASSWORD VARCHAR NOT NULL,
   SALT VARCHAR,
   FIRSTNAME VARCHAR NOT NULL,
   LASTNAME VARCHAR NOT NULL,
   EMAIL VARCHAR NOT NULL UNIQUE,
   STATUS smallint NOT NULL,
   CREATEDON timestamp with time zone,
   MOBILE bigint NOT NULL,
   CHANGEDON timestamp with time zone
)