/*
 * This file is generated by jOOQ.
 */
package com.example.models.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUsers extends Serializable {

    /**
     * Getter for <code>public.users.user_id</code>.
     */
    public Integer getUserId();

    /**
     * Getter for <code>public.users.username</code>.
     */
    @NotNull
    public String getUsername();

    /**
     * Getter for <code>public.users.password</code>.
     */
    @NotNull
    public String getPassword();

    /**
     * Getter for <code>public.users.salt</code>.
     */
    public String getSalt();

    /**
     * Getter for <code>public.users.firstname</code>.
     */
    @NotNull
    public String getFirstname();

    /**
     * Getter for <code>public.users.lastname</code>.
     */
    @NotNull
    public String getLastname();

    /**
     * Getter for <code>public.users.email</code>.
     */
    @NotNull
    public String getEmail();

    /**
     * Getter for <code>public.users.status</code>.
     */
    @NotNull
    public Short getStatus();

    /**
     * Getter for <code>public.users.createdon</code>.
     */
    public OffsetDateTime getCreatedon();

    /**
     * Getter for <code>public.users.mobile</code>.
     */
    @NotNull
    public Long getMobile();

    /**
     * Getter for <code>public.users.changedon</code>.
     */
    public OffsetDateTime getChangedon();
}
